[package]
name = "find-server"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
futures = "0.3.31"
reqwest = "0.12.22"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
